name: build-windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          profile: minimal
      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build and bundle
        run: ./scripts/build-windows.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stewart-sim-windows
          path: dist/windows
